postgres:
  build: ../postgres/
  environment:
    POSTGRES_PASSWORD: 1111

jenkins:
  image: jenkins
  ports:
  - "8080:8080"
  - "50000:50000"
  links:
  - postgres
  volumes:
  - /var/jenkins_home:/var/jenkins_home